  [[main]]
  name = "About"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Tutorials"
  weight = 300
  identifier = "tutorials"
  url = "/tutorials/"


  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"

#  [[footer]]
#  name = "imprint"
#  weight = 1
#  identifier = "imprint"
#  url = "/imprint/"